# Generated by Django 3.2.3 on 2021-06-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0006_saleproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='saleproducts',
            new_name='sproducts',
        ),
    ]
